### ISSUE TITLE
BUG: Headers missing on mobile

### ISSUE THREAD

**Issue by koderik** [isektionen/iare-se#74]
**Describe the bug**
Content in header not the same on mobile dropdown version

**To Reproduce**
Goto website on phone
Open dropdown menu
Headers are missing

**Expected behavior**
Headers should be the same as on computer

**Screenshots**
_On computer_
<img width="1333" alt="Screenshot 2022-11-16 at 13 29 16" src="https://user-images.githubusercontent.com/77754074/202180924-5bb5076f-69e0-4c69-b349-3ca137e63b57.png">
_On phone_
<img width="297" alt="Screenshot 2022-11-16 at 13 29 35" src="https://user-images.githubusercontent.com/77754074/202180996-529d3b06-b77e-4e75-9e6f-f636d214239f.png">

**Hardware**
OS: Mac
Browser Chrome

**Additional context**

**Comment by EmilSunnerdahl** [comment]
![image](https://user-images.githubusercontent.com/115029466/202193279-71085a44-f26c-471b-9219-4fa634c6f1a1.png)
Added the headers to mobile navbar in a way that is functional but not optimal user experience. The mobile page have a loop that only displays links that has subsections, which is why we added a subsection to every header link, and then toggled displayDropDown to off to avoid a drop down section on computer pages.
